apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
spec:
  selector:
    app: mssql-linux
  ports:
  - name: sqlserver
    port: 1433
    protocol: TCP
    targetPort: 1433
    nodePort: 30000
  type: NodePort
