kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "citus.fullname" . }}
  labels:
    {{- include "citus.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}